version: '3.9'

services:
  mssql:
    platform: linux/x86_64
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      MSSQL_SA_PASSWORD: admin.Pass
      ACCEPT_EULA: Y
      MSSQL_PID: Express
    ports:
      - 1433:1433
    volumes:
      - mssql-db-data:/var/lib/mssql

volumes:
  mssql-db-data:
    driver: local
